import type { Product, ProductId, ReviewInput, AnalysisRun } from "@venture-lab/domain-types";

export const products: Product[] = [
  { id:"legacy-parity-room", rank:1, name:"Legacy Parity Room", tagline:"Recover hidden business rules and turn them into verified parity tests.", buyer:"Modernization consultants · public-sector IT · application owners", price:"Starting at $4,000 for a bounded rule-recovery sprint", accent:"#f07b57", nav:["Overview","Rule catalog","Parity tests","Ambiguity register"], metrics:[{label:"Rules extracted",value:"184"},{label:"Verified",value:"72%"},{label:"Ambiguous",value:"12"}], records:[{title:"Permit transfer eligibility",detail:"A transfer is permitted when the holder is active and the receiving district is in the approved service area.",status:"needs_review",meta:"COBOL · line 1842 · 3 sources"},{title:"Estate holder display logic",detail:"Suppress address details when the account has an approved privacy flag.",status:"approved",meta:"SQL procedure · SME confirmation"},{title:"Opt-out address masking",detail:"Public exports replace address fields with district-level geography.",status:"unreviewed",meta:"Runtime log · 2 dependent rules"}], api:["POST /projects","GET /projects/:id/rules","POST /rules/:id/reviews","POST /projects/:id/exports"] },
  { id:"agent-safe-data-gateway", rank:2, name:"Agent-Safe Data Gateway", tagline:"Expose useful data to agents without exposing the underlying database.", buyer:"IT administrators · security engineers · AI program leads", price:"Starting at $3,000 for a read-only gateway pilot", accent:"#2abf9c", nav:["Gateway overview","Data contracts","Policy builder","Request ledger"], metrics:[{label:"Active contracts",value:"18"},{label:"Blocked requests",value:"47"},{label:"Avg latency",value:"118ms"}], records:[{title:"Permit search contract",detail:"Read-only access to permit status and district, with address redaction and a 250-row ceiling.",status:"approved",meta:"Oracle · owner: Permitting"},{title:"Bulk export request",detail:"Requested 12 fields for an unbounded export without a purpose code.",status:"rejected",meta:"Blocked · cost budget exceeded"},{title:"Eligibility assistant",detail:"Purpose-bound access to normalized eligibility fields for case triage.",status:"needs_review",meta:"PostgreSQL · expires in 14 days"}], api:["GET /data-sources","POST /contracts","POST /requests/simulate","POST /clients/:id/pause"] },
  { id:"public-data-evidence-room", rank:3, name:"Public-Data Evidence Room", tagline:"Bind every important claim to sources, versions, transformations, and review.", buyer:"Program managers · consultants · boards · research teams", price:"Starting at $1,500 for a bounded evidence audit", accent:"#7076ef", nav:["Document overview","Claim inventory","Findings","Source library"], metrics:[{label:"Claims checked",value:"96"},{label:"Evidence coverage",value:"88%"},{label:"Critical gaps",value:"4"}], records:[{title:"Population grew fastest in the region",detail:"The source supports growth, but no comparator is provided for the superlative claim.",status:"partially_supported",meta:"Page 4 · qualification suggested"},{title:"2025 employment figure",detail:"The cited dataset was revised after publication and the report uses the prior vintage.",status:"stale",meta:"Page 7 · BLS revision"},{title:"Median income increased 14%",detail:"Value and geography match the linked ACS table and publication period.",status:"supported",meta:"Page 9 · source verified"}], api:["POST /documents","GET /documents/:id/claims","POST /claims/:id/reviews","POST /documents/:id/exports"] },
  { id:"knowledge-succession-room", rank:4, name:"Knowledge Succession Room", tagline:"Capture critical institutional knowledge before experts retire or leave.", buyer:"Department heads · operations managers · workforce planners", price:"Starting at $3,000 for one role or workflow capture", accent:"#e8ad48", nav:["Succession dashboard","Expert directory","Interview workspace","Workflow map","Knowledge gaps"], metrics:[{label:"Workflows mapped",value:"23"},{label:"Knowledge gaps",value:"11"},{label:"Experts enrolled",value:"7"}], records:[{title:"Month-end reconciliation",detail:"Trigger, source reports, exception handling, and escalation contact are mapped.",status:"approved",meta:"Maria Chen · 8 steps"},{title:"Emergency permit override",detail:"The decision threshold is known only to one expert and needs a recorded exercise.",status:"needs_review",meta:"High risk · follow-up due Aug 14"},{title:"Legacy batch recovery",detail:"A recovery runbook is linked, but the restart condition is not validated.",status:"unreviewed",meta:"2 documents · 1 interview"}], api:["GET /experts","POST /experts/:id/interviews","GET /workflows","POST /knowledge-gaps","POST /transition-packets"] },
  { id:"policy-impact-mapper", rank:5, name:"Policy Impact Mapper", tagline:"Translate a policy change into affected systems, forms, workflows, and owners.", buyer:"Policy analysts · program managers · compliance leads", price:"Starting at $2,500 for one bounded policy packet", accent:"#df608e", nav:["Policy overview","Requirements","Impact matrix","Dependency timeline","Ambiguity register"], metrics:[{label:"Requirements",value:"38"},{label:"Affected assets",value:"64"},{label:"Open ambiguities",value:"6"}], records:[{title:"Eligibility notice must include appeal window",detail:"A new notice field is required for affected applicants beginning October 1.",status:"needs_review",meta:"Section 4.2 · owner: Benefits"},{title:"Public guidance revision",detail:"The public webpage and two forms need coordinated language updates.",status:"unreviewed",meta:"Dependency: legal interpretation"},{title:"Training material exception",detail:"The directive permits a phased rollout for existing cases.",status:"approved",meta:"Section 7 · evidence linked"}], api:["POST /policies","GET /policies/:id/requirements","PATCH /requirements/:id","GET /policies/:id/impacts","POST /policies/:id/exports"] }
];

export const getProduct = (id: ProductId) => products.find((product) => product.id === id) ?? products[0];
export class MockProductRepository {
  constructor(private product: Product) {}
  async getProduct() { return this.product; }
  async runAnalysis(): Promise<AnalysisRun> { return { id: `demo-${Date.now()}`, state:"complete", progress:100, message:"Demo analysis complete. Results are deterministic sample data." }; }
  async updateReview(input: ReviewInput) { return { ...input, savedAt: new Date().toISOString() }; }
  async exportPacket() { return { filename: `${this.product.id}-demo-packet.pdf`, status:"ready" as const }; }
}
