import type { Product, ProductId, ReviewInput, AnalysisRun } from "@venture-lab/domain-types";

export const products: Product[] = [
  { id:"legacy-parity-room", rank:1, name:"Legacy Parity Room", tagline:"Recover hidden business rules and prove that modernized systems preserve required behavior", description:"Trace rules to code, SQL, documents, runtime evidence, and expert review, then turn approved findings into regression tests and parity packets", buyer:"Modernization consultants · public-sector IT · application owners", price:"Starting at $4,000 for a bounded rule-recovery sprint", accent:"#f07b57", demoUrl:"https://legacy-parity-room.vercel.app", nav:["Overview","Rule catalog","Parity tests","Ambiguity register"], metrics:[{label:"Rules extracted",value:"184"},{label:"Verified",value:"72%"},{label:"Ambiguous",value:"12"}], records:[{title:"Permit transfer eligibility",detail:"A transfer is permitted when the holder is active and the receiving district is in the approved service area.",status:"needs_review",meta:"COBOL · line 1842 · 3 sources"},{title:"Estate holder display logic",detail:"Suppress address details when the account has an approved privacy flag.",status:"approved",meta:"SQL procedure · SME confirmation"},{title:"Opt-out address masking",detail:"Public exports replace address fields with district-level geography.",status:"unreviewed",meta:"Runtime log · 2 dependent rules"}], api:["POST /projects","GET /projects/:id/rules","POST /rules/:id/reviews","POST /projects/:id/exports"] },
  { id:"main-street-continuity", rank:2, name:"Main Street Continuity", tagline:"Make an owner-dependent business operable, transferable, and ready for an unexpected absence", description:"Capture critical decisions, relationships, access plans, recurring obligations, and exception handling, then produce a 30–90 day continuity binder and a practical exit-readiness roadmap", buyer:"Established business owners · CPAs/advisors · community banks · business brokers", price:"Starting at $950 for a bounded continuity audit", accent:"#e8ad48", demoUrl:"https://knowledge-succession-room.vercel.app", nav:["Continuity dashboard","Dependency map","Operations binder","Transition roadmap"], metrics:[{label:"Owner dependency",value:"78%"},{label:"Critical workflows",value:"14"},{label:"Unassigned risks",value:"6"}], records:[{title:"Payroll approval depends on owner",detail:"The payroll provider is documented, but only the owner can approve the final run and no emergency delegate is authorized.",status:"needs_review",meta:"Finance · due before next payroll"},{title:"Top customer relationship handoff",detail:"The company’s largest account relies on informal owner communication and has no documented backup relationship.",status:"unreviewed",meta:"31% of annual revenue · high concentration"},{title:"Emergency access and vendor contacts",detail:"Critical account recovery steps, vendor escalation contacts, and insurance details are stored in the approved continuity binder.",status:"approved",meta:"Binder section 2 · reviewed Aug 1"}], api:["POST /businesses","GET /businesses/:id/dependencies","POST /continuity-audits","PATCH /risks/:id","POST /continuity-packets"] },
  { id:"local-compliance-concierge", rank:3, name:"Local Compliance Concierge", tagline:"Keep licenses, permits, certifications, inspections, and insurance renewals current without another dashboard", description:"Forward notices by email, photo, mail, or fax; the concierge verifies the requirement, tracks the deadline, prepares the filing, requests approval, and stores completion evidence", buyer:"Contractors · restaurants · childcare · home care · property managers", price:"Starting at $249 per month plus filing fees", accent:"#2abf9c", demoUrl:"https://agent-safe-data-gateway.vercel.app", nav:["Compliance overview","Obligation register","Renewal queue","Evidence binder"], metrics:[{label:"Active obligations",value:"37"},{label:"Due in 30 days",value:"5"},{label:"Evidence complete",value:"92%"}], records:[{title:"Contractor license renewal",detail:"The state license expires September 30; the application is prepared and waiting for the owner’s approval and fee authorization.",status:"needs_review",meta:"Alaska DCCED · due in 27 days"},{title:"Commercial general liability certificate",detail:"The updated certificate was received from the broker and linked to the municipal contractor registration.",status:"approved",meta:"Policy period 2026–2027 · evidence stored"},{title:"Municipal business-license notice",detail:"The mailed notice appears legitimate, but the revenue classification differs from the prior filing and requires verification.",status:"unreviewed",meta:"City filing · classification question"}], api:["POST /businesses/:id/notices","GET /businesses/:id/obligations","PATCH /obligations/:id","POST /renewals/:id/approval","POST /evidence-binders"] },
  { id:"public-data-evidence-room", rank:4, name:"Public-Data Evidence Room", tagline:"Verify that every material claim is supported by current, correctly scoped evidence", description:"Connect report language to source versions, geographies, periods, transformations, and reviewer decisions while flagging stale, contradictory, or overstated conclusions", buyer:"Program managers · consultants · boards · research teams", price:"Starting at $1,500 for a bounded evidence audit", accent:"#7076ef", demoUrl:"https://public-data-evidence-room.vercel.app", nav:["Document overview","Claim inventory","Findings","Source library"], metrics:[{label:"Claims checked",value:"96"},{label:"Evidence coverage",value:"88%"},{label:"Critical gaps",value:"4"}], records:[{title:"Population grew fastest in the region",detail:"The source supports growth, but no comparator is provided for the superlative claim.",status:"partially_supported",meta:"Page 4 · qualification suggested"},{title:"2025 employment figure",detail:"The cited dataset was revised after publication and the report uses the prior vintage.",status:"stale",meta:"Page 7 · BLS revision"},{title:"Median income increased 14%",detail:"Value and geography match the linked ACS table and publication period.",status:"supported",meta:"Page 9 · source verified"}], api:["POST /documents","GET /documents/:id/claims","POST /claims/:id/reviews","POST /documents/:id/exports"] },
  { id:"policy-impact-mapper", rank:5, name:"Policy Impact Mapper", tagline:"Translate a policy change into affected systems, forms, workflows, and owners", description:"Extract source-linked requirements, map operational and technology impacts, surface ambiguities and dependencies, assign accountable owners, and build an implementation packet", buyer:"Policy analysts · program managers · compliance leads", price:"Starting at $2,500 for one bounded policy packet", accent:"#df608e", demoUrl:"https://policy-impact-mapper.vercel.app", nav:["Policy overview","Requirements","Impact matrix","Dependency timeline","Ambiguity register"], metrics:[{label:"Requirements",value:"38"},{label:"Affected assets",value:"64"},{label:"Open ambiguities",value:"6"}], records:[{title:"Eligibility notice must include appeal window",detail:"A new notice field is required for affected applicants beginning October 1.",status:"needs_review",meta:"Section 4.2 · owner: Benefits"},{title:"Public guidance revision",detail:"The public webpage and two forms need coordinated language updates.",status:"unreviewed",meta:"Dependency: legal interpretation"},{title:"Training material exception",detail:"The directive permits a phased rollout for existing cases.",status:"approved",meta:"Section 7 · evidence linked"}], api:["POST /policies","GET /policies/:id/requirements","PATCH /requirements/:id","GET /policies/:id/impacts","POST /policies/:id/exports"] }
];

export const getProduct = (id: ProductId) => products.find((product) => product.id === id) ?? products[0];
export class MockProductRepository {
  constructor(private product: Product) {}
  async getProduct() { return this.product; }
  async runAnalysis(): Promise<AnalysisRun> { return { id: `demo-${Date.now()}`, state:"complete", progress:100, message:"Demo analysis complete. Results are deterministic sample data." }; }
  async updateReview(input: ReviewInput) { return { ...input, savedAt: new Date().toISOString() }; }
  async exportPacket() { return { filename: `${this.product.id}-demo-packet.pdf`, status:"ready" as const }; }
}
